---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[poise-appenv_test]
- name: prod
  run_list:
  - recipe[poise-appenv_test::prod]
- name: test
  run_list:
  - recipe[poise-appenv_test::test]
- name: extra
  run_list:
  - recipe[poise-appenv_test::extra]
